INSERT INTO account (full_name, title, email, password, affiliation, job_type, country, city, address, zip_code, is_admin) VALUES
('root', 'Mr.R', 'root@unipu.hr', '$2a$12$rlJYGCjNYJpyZTt/enAIVuaI2JOdCyN93jQbE/hQQjIDLPTXmIOoC', 'root Affiliation', 'root job type', 'root country', 'root city', 'root address', 'root zip code', false),
('admin first', 'Mr.A1', 'admin1@unipu.hr', 'admin_password', 'admin1 Affiliation', 'admin1 job type', 'admin1 country', 'admin1 city', 'admin1 address', 'admin1 zip code', true),
('admin second', 'Mr.A2', 'admin2@unipu.hr', 'admin_password2',  'admin2 Affiliation', 'admin2 job type', 'admin2 country', 'admin2 city', 'admin2 address', 'admin2 zip code', true),
('new admin', 'Mr.A2', 'new.admin@unipu.hr', 'new_admin_password',  'admin2 Affiliation', 'admin2 job type', 'admin2 country', 'admin2 city', 'admin2 address', 'admin2 zip code', false),
('revoke admin', 'Mr.A2', 'revoke.admin@unipu.hr', 'revoked_admin_password',  'admin2 Affiliation', 'admin2 job type', 'admin2 country', 'admin2 city', 'admin2 address', 'admin2 zip code', true),
('first eic on publication', 'Mr.E1', 'eic1.on.publication@unipu.hr', 'eic_on_publication_password1', 'EiC1 Affiliation', 'EiC1 job type', 'EiC1 country', 'EiC1 city', 'EiC1 address', 'EiC1 zip code', false),
('second eic on publication', 'Mr.E2', 'eic2.on.publication@unipu.hr', 'eic_on_publication_password2', 'EiC2 Affiliation', 'EiC2 job type', 'EiC2 country', 'EiC2 city', 'EiC2 address', 'EiC2 zip code', false),
('new eic on publication', 'Mr.NE', 'new.eic.on.publication@unipu.hr', 'new_eic_on_publication_password2', 'new EiC2 Affiliation', 'new EiC2 job type', 'new EiC2 country', 'new EiC2 city', 'new EiC2 address', 'new EiC2 zip code', false),
('first section editor', 'Mr.SE1', 'section.editor1.publication@unipu.hr', 'section_editor_password1', 'section editor1 Affiliation', 'section editor1 job type', 'section editor1 country', 'section editor1 city', 'section editor1 address', 'section editor1 zip code', false),
('second section editor', 'Mr.SE2', 'section.editor2.publication@unipu.hr', 'section_editor_password2', 'section editor2 Affiliation', 'section editor2 job type', 'section editor2 country', 'section editor2 city', 'section editor2 address', 'section editor2 zip code', false),
('eic on manuscript1', 'Mr.EOP1', 'eic.on.manuscript1.manuscript@unipu.hr', 'eic_on_manuscript_password1', 'eic on manuscript1 Affiliation', 'eic on manuscript1 job type', 'eic on manuscript1 country', 'eic on manuscript1 city', 'eic on manuscript1 address', 'eic on manuscript1 zip code', false),
('eic on manuscript2', 'Mr.EOP2', 'eic.on.manuscript2.manuscript@unipu.hr', 'eic_on_manuscript_password2', 'eic on manuscript2 Affiliation', 'eic on manuscript2 job type', 'eic on manuscript2 country', 'eic on manuscript2 city', 'eic on manuscript2 address', 'eic on manuscript2 zip code', false),
('editor on manuscript1', 'Mr.EOP1', 'editor.on.manuscript1.manuscript@unipu.hr', 'editor_on_manuscript_password1', 'editor on manuscript1 Affiliation', 'editor on manuscript1 job type', 'editor on manuscript1 country', 'editor on manuscript1 city', 'editor on manuscript1 address', 'editor on manuscript1 zip code', false),
('editor on manuscript2', 'Mr.EOP2', 'editor.on.manuscript2.manuscript@unipu.hr', 'editor_on_manuscript_password2', 'editor on manuscript2 Affiliation', 'editor on manuscript2 job type', 'editor on manuscript2 country', 'editor on manuscript2 city', 'editor on manuscript2 address', 'editor on manuscript2 zip code', false),
('reviewer on manuscript1', 'Mr.EOP1', 'reviewer.on.manuscript1.manuscript@unipu.hr', 'reviewer_on_manuscript_password1', 'reviewer on manuscript1 Affiliation', 'reviewer on manuscript1 job type', 'reviewer on manuscript1 country', 'reviewer on manuscript1 city', 'reviewer on manuscript1 address', 'reviewer on manuscript1 zip code', false),
('reviewer on manuscript2', 'Mr.EOP2', 'reviewer.on.manuscript2.manuscript@unipu.hr', 'reviewer_on_manuscript_password2', 'reviewer on manuscript2 Affiliation', 'reviewer on manuscript2 job type', 'reviewer on manuscript2 country', 'reviewer on manuscript2 city', 'reviewer on manuscript2 address', 'reviewer on manuscript2 zip code', false),
('corresponding author on manuscript1', 'Mr.EOP1', 'corresponding.author.on.manuscript1.manuscript@unipu.hr', 'corresponding_author_on_manuscript_password1', 'corresponding author on manuscript1 Affiliation', 'corresponding author on manuscript1 job type', 'corresponding author on manuscript1 country', 'corresponding author on manuscript1 city', 'corresponding author on manuscript1 address', 'corresponding author on manuscript1 zip code', false),
('corresponding author on manuscript2', 'Mr.EOP2', 'corresponding.author.on.manuscript2.manuscript@unipu.hr', 'corresponding_author_on_manuscript_password2', 'corresponding author on manuscript2 Affiliation', 'corresponding author on manuscript2 job type', 'corresponding author on manuscript2 country', 'corresponding author on manuscript2 city', 'corresponding author on manuscript2 address', 'corresponding author on manuscript2 zip code', false),
('author on manuscript1', 'Mr.A1', 'author.on.manuscript1@unipu.hr', 'author_on_manuscript_password1', 'author1 Affiliation', 'author1 job type', 'author1 country', 'author1 city', 'author1 address', 'author1 zip code', false),
('author on manuscript2', 'Mr.A2', 'author.on.manuscript2@unipu.hr', 'author_on_manuscript_password2', 'author2 Affiliation', 'author2 job type', 'author2 country', 'author2 city', 'author2 address', 'author2 zip code', false),
('user first', 'Mr.U1', 'user1@unipu.hr', 'user_password1', 'Affiliation1', 'job type1', 'country1', 'city1', 'address1', 'zip code1', false),
('user second', 'Mr.U2', 'user2@unipu.hr', 'user_password2', 'Affiliation2', 'job type2', 'country2', 'city2', 'address2', 'zip code2', false),
('user third', 'Mr.U3', 'user3@unipu.hr', 'user_password3', 'Affiliation3', 'job type3', 'country3', 'city3', 'address3', 'zip code3', false),
('author for new manuscript', 'Mr.author for new manuscript', 'author.for.new.manuscript@unipu.hr', 'author_for_new_manuscript_password', 'author for new manuscript affiliation', 'author for new manuscript job type', 'author for new manuscript country', 'author for new manuscript country', 'author for new manuscript city', 'author for new manuscript zip code', false),
('EiC on first and eleventh, editor on second, reviewer on third', 'Mr.EiC on first and eleventh, editor on second, reviewer on third', 'EiC.on.first.editor.on.second.reviewer.on.third@unipu.hr', 'eic_editor_reviewer_password', 'EiC editor reviewer affiliation', 'EiC editor reviewer job type', 'EiC editor reviewer country', 'EiC editor reviewer country', 'EiC editor reviewer city', 'EiC editor reviewer zip code', false),
('reviewer on first and eleventh, EiC on second, editor on third', 'Mr.reviewer on first and eleventh, EiC on second, editor on third', 'reviewer.on.first.EiC.on.second.editor.on.third@unipu.hr', 'reviewer_eic_editor_password', 'reviewer EiC editor affiliation', 'reviewer EiC editor job type', 'reviewer EiC editor country', 'reviewer EiC editor country', 'reviewer EiC editor city', 'reviewer EiC editor zip code', false),
('editor on first and eleventh, reviewer on second, EiC on third', 'Mr.editor on first and eleventh, reviewer on second, EiC on third', 'editor.on.first.reviewer.on.second.EiC.on.third@unipu.hr', 'editor_reviewer_eic_password', 'editor reviewer EiC affiliation', 'editor reviewer EiC job type', 'editor reviewer EiC country', 'editor reviewer EiC country', 'editor reviewer EiC city', 'editor reviewer EiC zip code', false);
INSERT INTO invite (email, target, target_id) VALUES
('invited.admin1@unipu.hr', 'ADMIN', NULL),
('invited.admin2@unipu.hr', 'ADMIN', NULL),
('invited.eic.on.publication1@unipu.hr', 'EIC_ON_PUBLICATION', 1),
('invited.eic.on.publication2@unipu.hr', 'EIC_ON_PUBLICATION', 2),
('invited.eic.on.publication3@unipu.hr', 'EIC_ON_PUBLICATION', 3),
('invited.eic.on.manuscript1@unipu.hr', 'EIC_ON_MANUSCRIPT', 1),
('invited.eic.on.manuscript2@unipu.hr', 'EIC_ON_MANUSCRIPT', 2),
('invited.eic.on.manuscript2@unipu.hr', 'EIC_ON_MANUSCRIPT', 3),
('invited.section.editor.on.section1@unipu.hr', 'SECTION_EDITOR_ON_SECTION', 1),
('invited.section.editor.on.section2@unipu.hr', 'SECTION_EDITOR_ON_SECTION', 2),
('invited.section.editor.on.section3@unipu.hr', 'SECTION_EDITOR_ON_SECTION', 3),
('invited.editor.on.manuscript1@unipu.hr', 'EDITOR_ON_MANUSCRIPT', 1),
('invited.editor.on.manuscript2@unipu.hr', 'EDITOR_ON_MANUSCRIPT', 2),
('invited.editor.on.manuscript3@unipu.hr', 'EDITOR_ON_MANUSCRIPT', 3),
('invited.reviewer.on.manuscript1@unipu.hr', 'REVIEWER_ON_MANUSCRIPT', 1),
('invited.reviewer.on.manuscript2@unipu.hr', 'REVIEWER_ON_MANUSCRIPT', 2),
('invited.reviewer.on.manuscript3@unipu.hr', 'REVIEWER_ON_MANUSCRIPT', 3),
('invited.manuscript.role.1.2.3@unipu.hr', 'EDITOR_ON_MANUSCRIPT', 1),
('invited.manuscript.role.1.2.3@unipu.hr', 'REVIEWER_ON_MANUSCRIPT', 2),
('invited.manuscript.role.1.2.3@unipu.hr', 'EIC_ON_MANUSCRIPT', 3);
INSERT INTO category (name) VALUES
('Computer Science'),
('Biology'),
('Physics'),
('Mathematics'),
('Chemistry');
INSERT INTO publication (title, is_hidden) VALUES
('Journal of AI Research', FALSE),
('Nature of Biology', FALSE),
('Physics Letters', FALSE),
('first hidden publication', TRUE),
('second hidden publication', TRUE),
('Published empty publication', FALSE);
INSERT INTO eic_on_publication (publication_id, eic_id) VALUES
(1, 7),
(2, 6),
(3, 7),
(4, 6),
(5, 7);
INSERT INTO publication_section (title, description, publication_id, is_hidden) VALUES
('Machine Learning', 'ML research and techniques', 1, TRUE),
('Deep Learning', 'Neural networks and deep learning models', 1, FALSE),
('Natural Language Processing', 'Language models and text analysis', 1, FALSE),
('Computer Vision', 'Image processing and visual recognition', 1, FALSE),

('Neuroscience', 'Brain and behavior research', 2, TRUE),
('Cognitive Neuroscience', 'Neural mechanisms of cognition', 2, FALSE),
('Neuropsychology', 'Brain function and psychological processes', 2, FALSE),
('Electrochemistry', 'Chemical reactions involving electricity', 2, FALSE),

('Theoretical Physics', 'Theoretical frameworks in physics', 3, FALSE),
('Quantum Physics', 'Quantum mechanics and related fields', 3, TRUE),
('Astrophysics', 'Study of celestial bodies and phenomena', 3, FALSE),
('Condensed Matter Physics', 'Properties of solids and liquids', 3, FALSE),

('Algebra', 'Algebraic structures and systems', 4, TRUE),
('Number Theory', 'Properties and relationships of numbers', 4, FALSE),
('Topology', 'Properties preserved under continuous deformations', 4, FALSE),
('Combinatorics', 'Counting, arrangement, and combination', 4, FALSE),

('Physical Chemistry', 'Chemical systems and physical properties', 5, FALSE),
('Biochemistry', 'Chemical processes within living organisms', 5, FALSE),
('Organic Chemistry', 'Organic molecules and reactions', 5, TRUE),
('Analytical Chemistry', 'Techniques for analyzing chemical substances', 5, FALSE);
INSERT INTO section_editor_on_section (section_editor_id, publication_section_id) VALUES
(9, 1),
(10, 2);
INSERT INTO manuscript (title, description, author_id, category_id, current_state, section_id, file_url, submission_date, publication_date, views, downloads) VALUES
('Machine Learning for Radiology', 'A study on using ML to detect anomalies in radiological images.', 10, 1, 'AWAITING_EIC_REVIEW', 1, 'http://example.com/ms1.pdf', '2025-09-28 13:28:00', NULL, 134, 25),
('Deep Learning in Genomics', 'Analyzes genomic sequences using deep neural networks to predict mutations.', 11, 1, 'AWAITING_EDITOR_REVIEW', 7, 'http://example.com/ms2.pdf', '2023-09-28 13:28:00', NULL, 245, 33),
('Natural Language Processing in Clinical Notes', 'Extracting insights from unstructured clinical data using NLP.', 10, 2, 'AWAITING_REVIEWER_REVIEW', 11, 'http://example.com/ms3.pdf', '2022-09-28 13:28:00' , NULL, 310, 47),
('AI-Powered Drug Discovery', 'Accelerating pharmaceutical research through predictive modeling.', 11, 2, 'MINOR', 1, 'http://example.com/ms4.pdf', '2025-09-28 13:28:00', NULL, 98, 19),
('Reinforcement Learning in Surgery', 'Simulating surgical procedures using reinforcement learning algorithms.', 10, 3, 'MAJOR', 1, 'http://example.com/ms5.pdf', '2021-09-28 13:28:00', NULL, 87, 12),
('AI in Medical Decision Making', 'Examining the implications of autonomous decision systems in healthcare.', 11, 3, 'PUBLISHED', 1, 'http://example.com/ms6.pdf', '2020-09-28 13:28:00', '2022-06-30 13:32:16', 512, 88),
('Predictive Analytics in Emergency Care', 'Forecasting patient outcomes in emergency rooms using AI.', 10, 4, 'REJECTED', 1, 'http://example.com/ms7.pdf', '2025-09-28 13:28:00', NULL, 45, 5),
('AI-Based Mental Health Assessment', 'Assessing mental health using sentiment analysis and behavioral data.', 11, 4, 'ARCHIVED', 1, 'http://example.com/ms8.pdf', '2019-09-28 13:28:00', '2025-06-30 13:30:00', 21, 3),
('Clinical Trial Optimization with AI', 'Optimizing patient recruitment and trial design using machine learning.', 10, 5, 'HIDDEN', 1, 'http://example.com/ms9.pdf', '2018-09-28 13:28:00', '2025-07-25 17:45:00', 60, 7),
('Wearable Technology and AI Integration', 'Leveraging real-time health data from wearables through AI.', 11, 5, 'DRAFT', 1, 'http://example.com/ms10.pdf', '2017-09-28 13:28:00', NULL, 75, 14),

('Machine Learning for Radiology2', 'A study on using ML to detect anomalies in radiological images.2', 10, 1, 'AWAITING_EIC_REVIEW', 2, 'http://example.com/ms21.pdf', '2016-09-28 13:28:00', NULL, 135, 26),
('Deep Learning in Genomics2', 'Analyzes genomic sequences using deep neural networks to predict mutations.2', 11, 1, 'AWAITING_EDITOR_REVIEW', 2, 'http://example.com/ms22.pdf', '2015-09-28 13:28:00', NULL, 246, 34),
('Natural Language Processing in Clinical Notes2', 'Extracting insights from unstructured clinical data using NLP.2', 10, 2, 'AWAITING_REVIEWER_REVIEW', 2, 'http://example.com/ms23.pdf', '2014-09-28 13:28:00', NULL, 311, 48),
('AI-Powered Drug Discovery2', 'Accelerating pharmaceutical research through predictive modeling.2', 11, 2, 'MINOR', 2, 'http://example.com/ms24.pdf', '2013-09-28 13:28:00', NULL, 99, 20),
('Reinforcement Learning in Surgery2', 'Simulating surgical procedures using reinforcement learning algorithms.2', 10, 3, 'MAJOR', 2, 'http://example.com/ms25.pdf', '2012-09-28 13:28:00', NULL, 88, 13),
('AI in Medical Decision Making2', 'Examining the implications of autonomous decision systems in healthcare.2', 11, 3, 'PUBLISHED', 2, 'http://example.com/ms26.pdf', '2011-09-28 13:28:00', '2025-06-30 13:32:16', 513, 89),
('Predictive Analytics in Emergency Care2', 'Forecasting patient outcomes in emergency rooms using AI.2', 10, 4, 'REJECTED', 2, 'http://example.com/ms27.pdf', '2010-09-28 13:28:00', NULL, 46, 6),
('AI-Based Mental Health Assessment2', 'Assessing mental health using sentiment analysis and behavioral data.2', 11, 4, 'ARCHIVED', 2, 'http://example.com/ms28.pdf', '2009-09-28 13:28:00', '2025-06-30 13:30:00', 22, 4),
('Clinical Trial Optimization with AI2', 'Optimizing patient recruitment and trial design using machine learning.2', 10, 5, 'HIDDEN', 2, 'http://example.com/ms29.pdf', '2008-09-28 13:28:00', '2025-07-25 17:45:00', 61, 8),
('Wearable Technology and AI Integration2', 'Leveraging real-time health data from wearables through AI.2', 11, 5, 'DRAFT', 2, 'http://example.com/ms210.pdf', '2007-09-28 13:28:00', NULL, 76, 15),
('Manuscript awaiting deletion', 'description of manuscript awaiting deletion', 11, 5, 'REJECTED', 2, 'http://example.com/ms210.pdf', '2007-09-28 13:28:00', NULL, 76, 15);
INSERT INTO account_role_on_manuscript (manuscript_id, account_id, account_role) VALUES
(1, 11, 'EIC'),
(2, 12, 'EIC'),
(1, 13, 'EDITOR'),
(2, 14, 'EDITOR'),
(1, 15, 'REVIEWER'),
(2, 16, 'REVIEWER'),
(1, 17, 'CORRESPONDING_AUTHOR'),
(2, 18, 'CORRESPONDING_AUTHOR'),
(1, 19, 'AUTHOR'),
(2, 20, 'AUTHOR'),
(1, 25, 'EIC'),
(1, 26, 'REVIEWER'),
(1, 27, 'EDITOR'),
(2, 25, 'EDITOR'),
(2, 26, 'EIC'),
(2, 27, 'REVIEWER'),
(3, 25, 'REVIEWER'),
(3, 26, 'EDITOR'),
(3, 27, 'EIC'),
(11, 25, 'EIC'),
(11, 26, 'REVIEWER'),
(11, 27, 'EDITOR');
INSERT INTO manuscript_review (
    manuscript_id, reviewer_id, round, novelty, significance, technical_quality, clarity,
    methodology, relevance_to_the_publication, language_quality, overall_mark,
    sufficient_background, appropriate_research_design, adequately_described,
    clearly_presented, supported_conclusions, conflict, plagiarism, llm, self_citation,
    appropriate_references, ethical_concerns, reviewer_comment, reviewer_comment_file_url,
    author_response, author_response_file_url, recommendation, review_date, author_response_date
) VALUES
(1, 1, 1, 'FOUR', 'FOUR', 'FIVE', 'FOUR', 'FIVE', 'FOUR', 'FOUR', 'FOUR', 'YES', 'YES', 'YES', 'YES', 'YES', FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, 'Excellent study with clear methodology.', 'http://example.com/rev1.pdf', 'Thank you!', 'http://example.com/res1.pdf', 'ACCEPT', '2020-02-28 13:28:00', '2022-02-28 13:28:00'),
(1, 2, 1, 'THREE', 'THREE', 'THREE', 'TWO', 'TWO', 'THREE', 'THREE', 'THREE', 'YES', 'CAN_BE_IMPROVED', 'CAN_BE_IMPROVED', 'YES', 'YES', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Needs clarification in methods.', 'http://example.com/rev2.pdf', 'Clarified section 2.', 'http://example.com/res2.pdf', 'MINOR', '2001-02-28 13:28:00', '2002-02-28 13:28:00'),
(1, 2, 2, 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'YES', 'YES', 'YES', 'YES', 'YES', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Interesting results.', 'http://example.com/rev3.pdf', 'Added extra details.', 'http://example.com/res3.pdf', 'MAJOR', '2003-02-28 13:28:00', '2004-02-28 13:28:00'),
(1, 2, 3, 'TWO', 'TWO', 'TWO', 'TWO', 'ONE', 'TWO', 'TWO', 'TWO', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Needs major restructuring.', 'http://example.com/rev5.pdf', 'Will restructure.', 'http://example.com/res5.pdf', 'ACCEPT', '2005-02-28 13:28:00', '2006-02-28 13:28:00'),
(1, 3, 1, 'THREE', 'THREE', 'TWO', 'THREE', 'THREE', 'THREE', 'THREE', 'THREE', 'YES', 'YES', 'YES', 'CAN_BE_IMPROVED', 'YES', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Check figures for accuracy.', 'http://example.com/rev4.pdf', 'Updated figures.', 'http://example.com/res4.pdf', 'REJECT', '2007-02-28 13:28:00', '2008-02-28 13:28:00'),
(1, 3, 2, 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'THREE', 'FOUR', 'FOUR', 'YES', 'YES', 'YES', 'YES', 'YES', FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, 'Solid work, minor typos.', 'http://example.com/rev6.pdf', 'Fixed typos.', 'http://example.com/res6.pdf', 'MINOR', '2009-02-28 13:28:00', '2010-02-28 13:28:00'),

(2, 1, 1, 'FOUR', 'FOUR', 'FIVE', 'FOUR', 'FIVE', 'FOUR', 'FOUR', 'FOUR', 'YES', 'YES', 'YES', 'YES', 'YES', TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Excellent study with clear methodology.', 'http://example.com/rev1.pdf', 'Thank you!', 'http://example.com/res1.pdf', 'ACCEPT', '2011-02-28 13:28:00', '2012-02-28 13:28:00'),
(2, 2, 1, 'THREE', 'THREE', 'THREE', 'TWO', 'TWO', 'THREE', 'THREE', 'THREE', 'YES', 'CAN_BE_IMPROVED', 'CAN_BE_IMPROVED', 'YES', 'YES', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Needs clarification in methods.', 'http://example.com/rev2.pdf', 'Clarified section 2.', 'http://example.com/res2.pdf', 'MINOR', '2013-02-28 13:28:00', '2014-02-28 13:28:00'),
(2, 2, 2, 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'YES', 'YES', 'YES', 'YES', 'YES', FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 'Interesting results.', 'http://example.com/rev3.pdf', 'Added extra details.', 'http://example.com/res3.pdf', 'MAJOR', '2015-02-28 13:28:00', '2016-02-28 13:28:00'),
(2, 3, 1, 'THREE', 'THREE', 'TWO', 'THREE', 'THREE', 'THREE', 'THREE', 'THREE', 'YES', 'YES', 'YES', 'CAN_BE_IMPROVED', 'YES', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Check figures for accuracy.', 'http://example.com/rev4.pdf', 'Updated figures.', 'http://example.com/res4.pdf', 'REJECT', '2017-02-28 13:28:00', '2018-02-28 13:28:00'),
(2, 2, 3, 'TWO', 'TWO', 'TWO', 'TWO', 'ONE', 'TWO', 'TWO', 'TWO', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', 'MUST_BE_IMPROVED', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 'Needs major restructuring.', 'http://example.com/rev5.pdf', 'Will restructure.', 'http://example.com/res5.pdf', 'ACCEPT', '2019-02-28 13:28:00', '2020-02-28 13:28:00'),
(2, 3, 2, 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'FOUR', 'THREE', 'FOUR', 'FOUR', 'YES', 'YES', 'YES', 'YES', 'YES', FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 'Solid work, minor typos.', 'http://example.com/rev6.pdf', 'Fixed typos.', 'http://example.com/res6.pdf', 'MINOR', '2021-02-28 13:28:00', '2022-02-28 13:28:00');
